import { StyleSheet } from "react-native";

const style = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonContainer: {
    position: 'absolute',
    left: 20,
    top: 20,
  },
  header: {
    fontFamily: 'Poppins',
    fontSize: 32,
    width: 370,
    fontWeight: 'bold',
    color: '#333',
    lineHeight: 45,
    textAlign: 'left',
    // padding: 5,
    paddingLeft: 5,
    marginLeft: 0,
  },
  inputContainer: {
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    padding: 0,
    width: '90%',
    height: 120,
  },
  inputContainerNumeroIdentidad: {
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    padding: 0,
    width: '90%',
    height: 150,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderRadius: 3,
    height: 57,
    width: 358,
    fontFamily: 'Poppins',
    fontSize: 16,
    fontWeight: '500',
    color: '#000',
    lineHeight: 20.8,
  },
  label: {
    fontFamily: 'Poppins',
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    lineHeight: 24,
    textAlign: 'left',
    paddingTop: 10,
  },
  labelNumeroIdentidad: {
    fontFamily: 'Poppins',
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    lineHeight: 24,
    textAlign: 'left',
    paddingBottom: 15,
    marginTop: 15,
  },
  formato: {
    marginVertical: 10,
  },
  buttonContainer: {
    marginTop: 20,
  },
  button: {
    backgroundColor: '#888888',
    borderRadius: 3,
    justifyContent: 'center',
    alignItems: 'center',
    height: 72,
    width: 358,
    fontFamily: 'Poppins',
    marginTop: 30,
    fontWeight: '600',
    color: '#fff',
    lineHeight: 24,
    textAlign: 'center',
  },
  placeholder: {
    fontSize: 20,
    fontWeight: '600',
    color: '#fff',
    lineHeight: 30,
    // paddingRight: 10,
    marginRight: 10,
  },
});

export default style;