import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  footer: {
    alignItems: 'end',
    justifyContent: 'end',
    bottom: 10,
    marginTop: 12,
    // width: '100%',
  },
  bannerContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    // width: '94%',
  },
  slidesContainer: {
    height: 400,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 30,
  },
  slideTwo: {
    height: 287.09,
    width: 350,
    backgroundColor: '#fff',
    borderRadius: 13.09,
    padding: '43, 9.82, 43, 9.82',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginBottom: 20,
    marginTop: 70,
    alignItems: 'center',
    justifyContent: 'center',
    
  },
  image: {
    width: 350,
    height: 250,
  },
  header: {
    fontFamily: 'Poppins',
    marginTop: 20,
    marginBottom: 0,
    marginHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 3.55,
    // alignItems: 'center',
    // justifyContent: 'center',
    // textAlign: 'center',
  },
  // headerTop: {
  //   height: 19,
  //   fontWeight: 'normal',
  //   fontSize: 12.44,
  //   lineHeight: 18.65,
  //   textAlign: 'center',
  //   color: '#4f4f4f',
  // },
  // headerBottom: {
  //   fontSize: 35.53,
  //   fontWeight: 'bold',
  //   color: '#333',
  //   textAlign: 'center',
  // },
  // graphContainer: {
  //   flexDirection: 'row',
  //   justifyContent: 'center',
  //   // alignItems: 'space-between',
  //   marginTop: 30,
  //   marginBottom: 0,
  //   marginHorizontal: 0,
  //   marginRight: 0,
  //   padding: 0,
  //   // width: 300,
  //   flexDirection: 'row',
  //   // alignItems: 'center',
  //   justifyContent: 'center',
  // },
  // singleDay: {
  //   flexDirection: 'column',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  // },
  // graphAmount: {
  //   backgroundColor: '#696969',
  //   borderRadius: 54.18,
  //   padding: '0, 3.55, 0, 3.55',
  //   gap: 8.88,
  //   transform: 'rotate(-90deg)',
  //   color: '#f4f4f4',
  //   fontSize: 10.66,
  //   // lineHeight: 15.99,
  //   fontWeight: 'normal',
  //   fontFamily: 'Poppins',
  //   flexDirection: 'column',
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   marginVertical: 30,
  //   // paddingHorizontal: 5,
  //   marginHorizontal: 0,
  // },
  // graphDay: {
  //   height: 13.32,
  //   fontSize: 10.66,
  //   lineHeight: 15.99,
  //   textAlign: 'center',
  //   color: '#696969',
  //   marginTop: 10,
  // },
});

export default styles;
